function SimulationPage({ mode, filled, loading, error, seasonResult, simulateSeason, worldCup, startWorldCup, nextWorldCupMatch, onResults }) {
  const isWorldCup = mode === "worldcup";
  const complete = isWorldCup ? worldCup?.finished : Boolean(seasonResult);
  const start = isWorldCup ? startWorldCup : simulateSeason;
  const actionLabel = worldCup?.phase === "group" ? `Play group matchday ${(worldCup.groupMatchday || 0) + 1}` : worldCup?.phase === "roundOf16" ? "Play Round of 16" : worldCup?.phase === "quarterFinal" ? "Play quarter-finals" : worldCup?.phase === "semiFinal" ? "Play semi-finals" : worldCup?.phase === "thirdPlace" ? "Play third-place match" : "Play final";
  const latestIsGroupMatch = worldCup?.match?.stage?.startsWith("Group");

  return <div className="simulation-page page-wrap"><section className="simulation-stage"><span className="eyebrow">{isWorldCup ? "World Cup journey" : "Premier League season"}</span><h1>{complete ? "Competition complete." : "The story starts here."}</h1><p>{isWorldCup ? "Take your XI through the group stage and the road to the final." : "Run your completed XI through a full 38-match Premier League campaign."}</p>{filled < 11 ? <p className="notice">Complete all eleven positions before starting a competition.</p> : !worldCup && !seasonResult ? <button className="primary-button" disabled={loading} onClick={start}>{loading ? "Preparing…" : isWorldCup ? "Start World Cup" : "Simulate season"}</button> : null}{error && <p className="error-message">{error}</p>}{isWorldCup && worldCup && <div className="match-journey"><div className="journey-rounds">{worldCup.rounds.map((round, index) => <span key={round} className={index < worldCup.currentRound ? "done" : index === worldCup.currentRound ? "current" : ""}>{round}</span>)}</div>{worldCup.match && <article className="latest-match"><span>{worldCup.match.stage}</span><strong>{worldCup.match.teamA} <b>{worldCup.match.score}</b> {worldCup.match.teamB}</strong><small>{latestIsGroupMatch ? worldCup.match.winner === "Draw" ? "Points shared" : `${worldCup.match.winner} take three points` : worldCup.match.penalties ? `${worldCup.match.winner} advance on penalties` : `${worldCup.match.winner} advance`}</small></article>}{worldCup.groups?.A && <div className="simulation-group-status"><span>Group stage</span><b>Matchday {worldCup.groupMatchday || 0} of 3</b></div>}{!worldCup.finished && <button className="primary-button" disabled={loading} onClick={nextWorldCupMatch}>{loading ? "Simulating…" : actionLabel}</button>}{worldCup.finished && <button className="primary-button" onClick={onResults}>View results</button>}</div>}{seasonResult && <div className="season-glance"><span>Final record</span><strong>{seasonResult.wins}–{seasonResult.draws}–{seasonResult.losses}</strong><small>{seasonResult.points} points · {seasonResult.goalsFor}:{seasonResult.goalsAgainst} goals</small><button className="primary-button" onClick={onResults}>View final table</button></div>}</section></div>;
}

export default SimulationPage;
